### PR TITLE
Update bitvec to 1.0.1

### LINKED ISSUE #24: Outdated bitvec dependency
Hi,

funty 1.2.0 has been yanked.
bitvec = "0.22" won't build.

Is it possible to update bitvec to the latest version ?

Thanks !

### PR DESCRIPTION
**Pull request by cecton**
Fixes #24

### CODE REVIEW

**Comment by cecton** [comment]
hey @bgilbert :wave: I'm always in doubt when updating dependencies. I think it would be fine to make a patch release for this fix because I don't change anything in the API of mbrman, only a dependency of ours is making breaking changes in their API?

**BUT** here, since I need to update the MSRV, I'm making a breaking change so I need to bump the major?

**Comment by r3dlight** [comment]
Hi,

I understand the need for backward compatibility, but IMHO 1.56 is already relatively old :)
What do you think?

**Comment by cecton** [comment]
I will just merge it for now as a patch release. In any case, nobody can build mbrman in its current state! Worst case scenario I will yank the version later

**Comment by cecton** [comment]
Released 0.5.1

**Comment by cecton** [comment]
I actually got the answer I was looking for on some other ticket https://github.com/rust-disk-partition-management/gptman/pull/113#issuecomment-1378867516

Since mbrman is in 0. version, I think the bump is fine

**Pull request merged**
